<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteRepository extends EntityRepository
{
    public function getCount()
    {
        $qb = $this->createQueryBuilder('r');

        return $qb
          ->select($qb->expr()->count('r'))
          ->getQuery()
          ->getSingleScalarResult();
    }

    public function getDistanceTotal()
    {
        $dql = sprintf('SELECT SUM(r.distance) FROM %s r', $this->getClassName());

        return $this->createQueryBuilder('r')
          ->getQuery()
          ->setDQL($dql)
          ->getSingleScalarResult();
    }
}
