<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShapeRepository extends EntityRepository
{
}
